# 2 - weather services
apiVersion: v1
kind: Service
metadata:
  name: weather-services
spec:
  type: ClusterIP
  ports:
    - name: services
      port: 80
      targetPort: 8081
  selector:
    app: weather-services
---
# microservices components 2 - api services
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-services
  name: weather-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-services
  template:
    metadata:
      labels:
        app: weather-services
    spec:
      containers:
        - image: brainupgrade/weather-services:jenkins-1
          imagePullPolicy: Always
          name: weather-services
          env:
            - name: spring.application.name
              value: weather-services
            - name: server.port
              value: "8081"
          ports:
            - containerPort: 8081
